version: 2
updates:
# Maintain dependencies for GitHub Actions.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
# Maintain dependencies for Dockerfiles.
  - package-ecosystem: "docker"
    directory: "/client"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
# Maintain dependencies for pip packages.
  - package-ecosystem: "pip"
    directory: "/client"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
