FROM python:3.13.7-alpine

ENV UV_LINK_MODE=copy
ENV UV_SYSTEM_PYTHON=1
ENV UV_COMPILE_BYTECODE=1

ENV DEVPISERVER_SERVERDIR=/devpi/server
RUN mkdir -p $DEVPISERVER_SERVERDIR && \
    mkdir /entrypoint.d

RUN --mount=from=ghcr.io/astral-sh/uv,source=/uv,target=/bin/uv \
    --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=requirements.txt,target=requirements.txt \
    uv pip install --system -r requirements.txt

COPY entrypoint.sh /
ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "" ]

EXPOSE 3141
